services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma  # ✅ use named volume here
    restart: unless-stopped

  multimodal-rag:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - chromadb
    restart: unless-stopped

# ✅ Declare the volume at the bottom
volumes:
  chroma_data:
