version: '3.8'

services:
  multimodal-rag:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./chroma:/app/app/chroma  # Make sure chroma persistence is mounted
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
